// Code generated by Evolver bounded executor (ADR-041). DO NOT edit by hand unless taking ownership.
package evolver

// ImplPlanNextEvolutionCycleBasedOn is an allowlisted implementation stub for a TaskPlan slice.
// Replace the body with real logic in a subsequent evolution cycle.
type ImplPlanNextEvolutionCycleBasedOn struct {
	TaskID string
	Title  string
}

// DescribeImplPlanNextEvolutionCycleBasedOn returns a stable summary used by regression tests.
func DescribeImplPlanNextEvolutionCycleBasedOn(taskID, title string) string {
	if taskID == "" {
		taskID = "task"
	}
	if title == "" {
		title = "untitled"
	}
	return taskID + ": " + title
}
